### ISSUE TITLE
hasicorp/yamux vs go-yamux

### ISSUE THREAD

**Issue by om26er** [libp2p/go-yamux#103]
Simple question, whats the different between the hashicorp project and this fork/implementation. Is there a recommendation on which version should be used

**Comment by Stebalien** [comment]
Too many to list at this point. I'm not sure they're even protocol compatible. If you're using go-libp2p, you _must_ use this one. If you're not, up to you.

This version:

- Adds many performance improvements. Especially reducing allocations and lock contention.
- Fixes some issues around half-open streams.

(I'm closing this issue but feel free to ask for clarification)
