### ISSUE TITLE
twice set for stream.readDeadline

### ISSUE THREAD

**Issue by terryding77** [libp2p/go-yamux#11]
https://github.com/libp2p/go-yamux/blob/736c1cb5f3388f502c6da5911f9784ee18f1266c/stream.go#L311-L325
https://github.com/libp2p/go-yamux/blob/736c1cb5f3388f502c6da5911f9784ee18f1266c/stream.go#L328-L333

I find in **Stream.forceClose** and **stream.cleanup** functions, we set the **readDeadline** twice, is there any trick for deadline? or it just the wrong typo for **writeDeadline**?

**Comment by Stebalien** [comment]
Nice catch! Yeah, that's wrong. It likely only leaked timers for a short period of time but still...

Mind submitting a PR to fix it?
