### ISSUE TITLE
Bug Report: Infinite Loop in yamux Write Function

### ISSUE THREAD

**Issue by frystal** [libp2p/go-yamux#111]
## Description:

An issue has been identified in the yamux library, specifically in the Write function. This issue arises when attempting to write a message to the remote peer using the "sendMsg" function. Before invoking the "sendMsg" function, the "write(b []byte)" function checks whether the "sendWindow" is equal to 0. However, in the scenario where the connection state is "halfOpen" and the "sendWindow" is zero due to an excessive number of communications on a single stream, it leads to an infinite loop between the "Write(b []byte)" and "write(b []byte)" functions.
![image](https://github.com/libp2p/go-yamux/assets/44425340/ff2f3991-b126-48da-9f53-e7df8cac1aec)
## Expected Outcome:

The Write function should handle the scenario of a zero "sendWindow" in the "halfOpen" connection state gracefully, without causing an infinite loop.

## Actual Outcome:

The current implementation leads to an infinite loop in the described scenario.

## Environment:
go-yamux@v4.0.1

**Comment by marten-seemann** [comment]
I'm not sure I understand why there would be an infinite loop. It can only loop when something is received from the `sendNotifyCh`. Who's continuously sending on this channel?

**Comment by frystal** [comment]
I apologize for any confusion. If I have a total message length of 500 bytes with a window size of 250, the first 250 bytes will be sent successfully. However, the remaining 250-byte message will not be sent and will become stuck in the 'select' operation without returning any error.

**Comment by marten-seemann** [comment]
That's how it's supposed to work. You need to wait until further flow control credit has been received before you send the remaining 250 bytes.

**Comment by frystal** [comment]
So you mean that users should manually handle the entire flow control credit? I haven't come across any automated flow control mechanisms in go-yamux. If I'm mistaken, I couldn't find any flow control implementation in go-libp2p-pubsub for stream either.
