### ISSUE TITLE
Bug Report:  Uint32 Overflow in sendWindow Calculation

### ISSUE THREAD

**Issue by frystal** [libp2p/go-yamux#112]
## Description:

A critical issue has been identified in the handling of the sending window size in the go-yamux library. The sending window size is calculated based on the initialStreamWindow (256*1024) added to the remote send window size from the Windows Update message. However, in the function "incrSendWindow", the value is incremented using atomic.AddUint32 without checking whether the sum might overflow due to the limitations of the uint32 data type. This could potentially lead to the sending window size overflowing to 0, rendering the stream incapable of sending any messages.

![image](https://github.com/libp2p/go-yamux/assets/44425340/8a527144-9ece-4ab0-81ac-0eb67ee58863)

## Environment:
go-yamux@v4.0.1

**Comment by marten-seemann** [comment]
Can you elaborate why you think this is a critical issue?

As far as I can tell, all that an attacker can do with this is reduce the size of the send window to a value smaller than the current value.

**Comment by frystal** [comment]
I think it is one trigger case of Issue#111.

**Comment by frystal** [comment]
While it may not be a critical issue, I believe it should be considered a bug.

**Comment by marten-seemann** [comment]
> I think it is one trigger case of Issue#111.

It most likely is not, at least not if your interop-ing with another go-yamux. The maximum window size is 16 MB, which is far below the maximum uint32.

**Comment by frystal** [comment]
I'm wondering if it might be true that if the user modifies and sends a window update message that exceeds the maximum uint32. Anyway, i think adding a check could make the code more robust

**Comment by marten-seemann** [comment]
Adding a check doesn't help. It just creates an inconsistent state between the peers. You could either close the connection in that case, or expand the uint32 to a uint64.

**Comment by frystal** [comment]
Could you please assign it the 'bug' label?
