### ISSUE TITLE
Send control messages on a control queue

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-yamux#19]
Currently, all messages go through the same send queue. Unfortunately, this means that low-latency, low-bandwidth, high-priority control messages get stuck behind data. We should send many control messages on a high-priority, out of order queue:

* Reset Just make sure we don't send this _before_ we send the open message or bad things might happen.
* Window updates. This is actually really important. At the moment, we could slow down _receiving_ data because we're busy sending it. That's _not_ good.
* Ping.

Importantly, we should _not_ send stream open/close requests on a separate channel as order matters.

**Comment by Stebalien** [comment]
Fixed in #22. We're only sending ping and reset but that should be good enough for now.

**Comment by willscott** [comment]
(ping and window-size updates). Close and Resets are put in-line so that channels don't close before the associated stream's data is delivered.
