### ISSUE TITLE
Panic due to nil check on memory manager not succeeding

### ISSUE THREAD

**Issue by hannahhoward** [libp2p/go-yamux#79]
We are seeing the following panic with go-yamux 3.0.2:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x187da42]

goroutine 601154 [running]:
github.com/libp2p/go-libp2p-resource-manager.(*peerScope).ReserveMemory(0x0, 0x0, 0xa0)
        <autogenerated>:1 +0x22
github.com/libp2p/go-yamux/v3.(*Session).incomingStream(0xc00931ad80, 0x2)
        /home/estuary/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:765 +0x8c
github.com/libp2p/go-yamux/v3.(*Session).handleStreamMessage(0xc00931ad80, {0x0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x2, 0x0, ...})
        /home/estuary/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:660 +0x86
github.com/libp2p/go-yamux/v3.(*Session).recvLoop(0xc00931ad80)
        /home/estuary/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:648 +0x148
github.com/libp2p/go-yamux/v3.(*Session).recv(0xc00314cf88)
        /home/estuary/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:602 +0x1e
created by github.com/libp2p/go-yamux/v3.newSession
        /home/estuary/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:157 +0x62f
exit status 2
```

It looks like this library already has code to deal with the memory manager being nil, but I'm guessing the nil check is failing due to interface conversion from network.PeerScope to MemoryManager that happens [here](https://github.com/libp2p/go-libp2p-yamux/blob/master/transport.go#L37) along with go's somewhat bizarre logic around nil equality ( see https://codefibershq.com/blog/golang-why-nil-is-not-always-nil)

Suggested possible fixes:
- use reflect in the nil check in this repo
- in the go-libp2p-yamux repo, change the transport initialization code to something like this:

```golang

func (t *Transport) NewConn(nc net.Conn, isServer bool, scope network.PeerScope) (network.MuxedConn, error) {
	var s *yamux.Session
	var err error
	var mm yamux.MemoryManager = scope
	if scope == nil {
	  mm = nil
	}
	if isServer {
		s, err = yamux.Server(nc, t.Config(), mm)
	} else {
		s, err = yamux.Client(nc, t.Config(), mm)
	}
	return (*conn)(s), err
}
```

**Comment by vyzo** [comment]
this fix is inappropriate, it is the scope that shouldnt be nil.

**Comment by hannahhoward** [comment]
Hey @vyzo any reason the scope is nil in 1.18.0rc2? We just initialized a libp2p host we mostly default options.

**Comment by hannahhoward** [comment]
thanks for your efforts. :) happy hunting.

**Comment by vyzo** [comment]
are you dealing with relay conns at all?

**Comment by vyzo** [comment]
Fix in https://github.com/libp2p/go-libp2p-transport-upgrader/pull/104

**Comment by vyzo** [comment]
Fixed in https://github.com/libp2p/go-libp2p/releases/tag/v0.18.0-rc3
